// 
// HyBid SDK License
//
// https://github.com/pubnative/pubnative-hybid-ios-sdk/blob/main/LICENSE
//

#import <Foundation/Foundation.h>

typedef NSString * HyBidVASTAdTrackingEventType;

// Player Operation Metrics
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_mute;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_unmute;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_pause;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_resume;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_rewind;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_click;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_skip;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_playerExpand;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_playerCollapse;

// Linear Ad Metrics

extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_loaded;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_start;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_firstQuartile;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_midpoint;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_thirdQuartile;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_complete;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_otherAdInteraction;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_progress;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_closeLinear;

// Non Linear Ad Metrics
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_acceptInvitation;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_adExpand;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_adCollapse;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_minimize;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_close;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_overlayViewDuration;

// Companign Ad Metrics
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_creativeView;
extern HyBidVASTAdTrackingEventType const HyBidVASTAdTrackingEventType_ctaClick;
