#ifndef NECORE_VERSION_H
#define NECORE_VERSION_H

#define NECORE_VERSION  "1.3"
#define NECORE_VERSION_MAJOR "1"
#define NECORE_VERSION_MINOR "3"
#define NECORE_VERSION_PATCH ""
#define NECORE_VERSION_TWEAK ""

#endif
