// Generated by Apple Swift version 5.5 (swiftlang-1300.0.31.1 clang-1300.0.29.1)
#ifndef HYBID_SWIFT_H
#define HYBID_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import CoreFoundation;
@import CoreLocation;
@import Foundation;
@import ObjectiveC;
@import StoreKit;
@import UIKit;
#endif

#import <HyBid.h>

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="HyBid",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class HyBidAdSessionData;
@class HyBidAdRequest;
@class HyBidAd;
@class NSString;
SWIFT_CLASS("_TtC5HyBid11ATOMManager")
@interface ATOMManager : NSObject
+ (void)fireAdSessionEventWithData:(HyBidAdSessionData * _Nonnull)data;
+ (HyBidAdSessionData * _Nonnull)createAdSessionDataFrom:(HyBidAdRequest * _Nullable)request ad:(HyBidAd * _Nonnull)ad SWIFT_WARN_UNUSED_RESULT;
+ (void)reportAdSessionDataSharedEventWithAdSessionDict:(NSDictionary<NSString *, id> * _Nonnull)adSessionDict;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid24HyBidReportingProperties")
@interface HyBidReportingProperties : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS_NAMED("AdFormat")
@interface HyBidReportingAdFormat : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull NATIVE;)
+ (NSString * _Nonnull)NATIVE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BANNER;)
+ (NSString * _Nonnull)BANNER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull FULLSCREEN;)
+ (NSString * _Nonnull)FULLSCREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REWARDED;)
+ (NSString * _Nonnull)REWARDED SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("BeaconType")
@interface HyBidReportingBeaconType : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CLICK;)
+ (NSString * _Nonnull)CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull IMPRESSION;)
+ (NSString * _Nonnull)IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_IMPRESSION;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_CLICK;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("Common")
@interface HyBidReportingCommon : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_FORMAT;)
+ (NSString * _Nonnull)AD_FORMAT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SIZE;)
+ (NSString * _Nonnull)AD_SIZE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CATEGORY_ID;)
+ (NSString * _Nonnull)CATEGORY_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CAMPAIGN_ID;)
+ (NSString * _Nonnull)CAMPAIGN_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EVENT_TYPE;)
+ (NSString * _Nonnull)EVENT_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CREATIVE_TYPE;)
+ (NSString * _Nonnull)CREATIVE_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TIMESTAMP;)
+ (NSString * _Nonnull)TIMESTAMP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull APPTOKEN;)
+ (NSString * _Nonnull)APPTOKEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ZONE_ID;)
+ (NSString * _Nonnull)ZONE_ID SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INTEGRATION_TYPE;)
+ (NSString * _Nonnull)INTEGRATION_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull KEY_MEDIATION_VENDOR;)
+ (NSString * _Nonnull)KEY_MEDIATION_VENDOR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull TIME_TO_LOAD;)
+ (NSString * _Nonnull)TIME_TO_LOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_TYPE;)
+ (NSString * _Nonnull)AD_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CACHE_TIME;)
+ (NSString * _Nonnull)CACHE_TIME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_REQUEST;)
+ (NSString * _Nonnull)AD_REQUEST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_RESPONSE;)
+ (NSString * _Nonnull)AD_RESPONSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RESPONSE_TIME;)
+ (NSString * _Nonnull)RESPONSE_TIME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REQUEST_TYPE;)
+ (NSString * _Nonnull)REQUEST_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RENDER_TIME;)
+ (NSString * _Nonnull)RENDER_TIME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_POSITION;)
+ (NSString * _Nonnull)AD_POSITION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ERROR_CODE;)
+ (NSString * _Nonnull)ERROR_CODE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ERROR_MESSAGE;)
+ (NSString * _Nonnull)ERROR_MESSAGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CREATIVE;)
+ (NSString * _Nonnull)CREATIVE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull HAS_END_CARD;)
+ (NSString * _Nonnull)HAS_END_CARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LAST_SESSION_TIMESTAMP;)
+ (NSString * _Nonnull)LAST_SESSION_TIMESTAMP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull IMPRESSION_SESSION_COUNT;)
+ (NSString * _Nonnull)IMPRESSION_SESSION_COUNT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull START_SESSION_TIMESTAMP;)
+ (NSString * _Nonnull)START_SESSION_TIMESTAMP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SESSION_DURATION;)
+ (NSString * _Nonnull)SESSION_DURATION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AGE_OF_APP;)
+ (NSString * _Nonnull)AGE_OF_APP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BEACON_TYPE;)
+ (NSString * _Nonnull)BEACON_TYPE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VAST_TRACKER_TYPE;)
+ (NSString * _Nonnull)VAST_TRACKER_TYPE SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("CreativeType")
@interface HyBidReportingCreativeType : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull STANDARD;)
+ (NSString * _Nonnull)STANDARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO;)
+ (NSString * _Nonnull)VIDEO SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("EventType")
@interface HyBidReportingEventType : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REQUEST;)
+ (NSString * _Nonnull)REQUEST SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull IMPRESSION;)
+ (NSString * _Nonnull)IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull OMID_IMPRESSION;)
+ (NSString * _Nonnull)OMID_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CLICK;)
+ (NSString * _Nonnull)CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ERROR;)
+ (NSString * _Nonnull)ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull INTERSTITIAL_CLOSED;)
+ (NSString * _Nonnull)INTERSTITIAL_CLOSED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REWARDED_CLOSED;)
+ (NSString * _Nonnull)REWARDED_CLOSED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_STARTED;)
+ (NSString * _Nonnull)VIDEO_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_DISMISSED;)
+ (NSString * _Nonnull)VIDEO_DISMISSED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_MUTE;)
+ (NSString * _Nonnull)VIDEO_MUTE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_UNMUTE;)
+ (NSString * _Nonnull)VIDEO_UNMUTE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_INITIALIZED;)
+ (NSString * _Nonnull)AD_SESSION_INITIALIZED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_LOADED;)
+ (NSString * _Nonnull)AD_SESSION_LOADED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_STARTED;)
+ (NSString * _Nonnull)AD_SESSION_STARTED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_STOPPED;)
+ (NSString * _Nonnull)AD_SESSION_STOPPED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_FIRST_QUARTILE;)
+ (NSString * _Nonnull)VIDEO_AD_FIRST_QUARTILE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_MIDPOINT;)
+ (NSString * _Nonnull)VIDEO_AD_MIDPOINT SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_THIRD_QUARTILE;)
+ (NSString * _Nonnull)VIDEO_AD_THIRD_QUARTILE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_COMPLETE;)
+ (NSString * _Nonnull)VIDEO_AD_COMPLETE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_PAUSE;)
+ (NSString * _Nonnull)VIDEO_AD_PAUSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_RESUME;)
+ (NSString * _Nonnull)VIDEO_AD_RESUME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_BUFFER_START;)
+ (NSString * _Nonnull)VIDEO_AD_BUFFER_START SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_BUFFER_FINISH;)
+ (NSString * _Nonnull)VIDEO_AD_BUFFER_FINISH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_VOLUME_CHANGE;)
+ (NSString * _Nonnull)VIDEO_AD_VOLUME_CHANGE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_SKIPPED;)
+ (NSString * _Nonnull)VIDEO_AD_SKIPPED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_AD_CLICKED;)
+ (NSString * _Nonnull)VIDEO_AD_CLICKED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LOAD;)
+ (NSString * _Nonnull)LOAD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull LOAD_FAIL;)
+ (NSString * _Nonnull)LOAD_FAIL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SHOW;)
+ (NSString * _Nonnull)SHOW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REPLAY;)
+ (NSString * _Nonnull)REPLAY SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CACHE;)
+ (NSString * _Nonnull)CACHE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RESPONSE;)
+ (NSString * _Nonnull)RESPONSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RENDER;)
+ (NSString * _Nonnull)RENDER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RENDER_ERROR;)
+ (NSString * _Nonnull)RENDER_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull COMPANION_VIEW;)
+ (NSString * _Nonnull)COMPANION_VIEW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull REWARD;)
+ (NSString * _Nonnull)REWARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SESSION_REPORT_INFO;)
+ (NSString * _Nonnull)SESSION_REPORT_INFO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_IMPRESSION;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_IMPRESSION_ERROR;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_IMPRESSION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEFAULT_ENDCARD_SKIP;)
+ (NSString * _Nonnull)DEFAULT_ENDCARD_SKIP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEFAULT_ENDCARD_CLOSE;)
+ (NSString * _Nonnull)DEFAULT_ENDCARD_CLOSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEFAULT_ENDCARD_IMPRESSION;)
+ (NSString * _Nonnull)DEFAULT_ENDCARD_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEFAULT_ENDCARD_IMPRESSION_ERROR;)
+ (NSString * _Nonnull)DEFAULT_ENDCARD_IMPRESSION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull DEFAULT_ENDCARD_CLICK;)
+ (NSString * _Nonnull)DEFAULT_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_CLOSE;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_CLOSE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_ENDCARD_CLICK;)
+ (NSString * _Nonnull)CUSTOM_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ATOM_ACTIVATED;)
+ (NSString * _Nonnull)ATOM_ACTIVATED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ATOM_DEACTIVATED;)
+ (NSString * _Nonnull)ATOM_DEACTIVATED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ATOM_ACTIVATED_RECEIVED;)
+ (NSString * _Nonnull)ATOM_ACTIVATED_RECEIVED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ATOM_DEACTIVATED_RECEIVED;)
+ (NSString * _Nonnull)ATOM_DEACTIVATED_RECEIVED SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_CTA_IMPRESSION;)
+ (NSString * _Nonnull)CUSTOM_CTA_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_CTA_CLICK;)
+ (NSString * _Nonnull)CUSTOM_CTA_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CUSTOM_CTA_ENDCARD_CLICK;)
+ (NSString * _Nonnull)CUSTOM_CTA_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SKOVERLAY_IMPRESSION;)
+ (NSString * _Nonnull)SKOVERLAY_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SKOVERLAY_IMPRESSION_ERROR;)
+ (NSString * _Nonnull)SKOVERLAY_IMPRESSION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull STOREKIT_PRODUCT_VIEW_DISMISS;)
+ (NSString * _Nonnull)STOREKIT_PRODUCT_VIEW_DISMISS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull STOREKIT_AUTOMATIC_CLICK;)
+ (NSString * _Nonnull)STOREKIT_AUTOMATIC_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull STOREKIT_AUTOMATIC_DEFAULT_ENDCARD_CLICK;)
+ (NSString * _Nonnull)STOREKIT_AUTOMATIC_DEFAULT_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull STOREKIT_AUTOMATIC_CUSTOM_ENDCARD_CLICK;)
+ (NSString * _Nonnull)STOREKIT_AUTOMATIC_CUSTOM_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SKOVERLAY_AUTOMATIC_CLICK;)
+ (NSString * _Nonnull)SKOVERLAY_AUTOMATIC_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SKOVERLAY_AUTOMATIC_DEFAULT_ENDCARD_CLICK;)
+ (NSString * _Nonnull)SKOVERLAY_AUTOMATIC_DEFAULT_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull SKOVERLAY_AUTOMATIC_CUSTOM_ENDCARD_CLICK;)
+ (NSString * _Nonnull)SKOVERLAY_AUTOMATIC_CUSTOM_ENDCARD_CLICK SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AUTO_STORE_KIT_IMPRESSION;)
+ (NSString * _Nonnull)AUTO_STORE_KIT_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AUTO_STORE_KIT_IMPRESSION_ERROR;)
+ (NSString * _Nonnull)AUTO_STORE_KIT_IMPRESSION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_AD_TYPE_MACRO;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_AD_TYPE_MACRO SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION_ERROR;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_HANDLE_TAP;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_HANDLE_TAP SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_HANDLE_TAP_ERROR;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_HANDLE_TAP_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION_BEGIN_VIEW;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION_BEGIN_VIEW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION_BEGIN_VIEW_ERROR;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION_BEGIN_VIEW_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION_END_VIEW;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION_END_VIEW SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_ATTRIBUTION_KIT_APP_IMPRESSION_END_VIEW_ERROR;)
+ (NSString * _Nonnull)AD_ATTRIBUTION_KIT_APP_IMPRESSION_END_VIEW_ERROR SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_DATA_SHARED_TO_ATOM;)
+ (NSString * _Nonnull)AD_SESSION_DATA_SHARED_TO_ATOM SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid27HyBidAAKNetworkRequestModel")
@interface HyBidAAKNetworkRequestModel : NSObject
- (NSString * _Nullable)getAAKNetworkIDsString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class UIView;
SWIFT_CLASS("_TtC5HyBid39HyBidAdAttributionCustomClickAdsWrapper")
@interface HyBidAdAttributionCustomClickAdsWrapper : NSObject
- (nonnull instancetype)initWithAd:(HyBidAd * _Nonnull)ad adFormat:(NSString * _Nullable)adFormat OBJC_DESIGNATED_INITIALIZER;
- (void)startImpressionWithAdView:(UIView * _Nullable)adView;
- (BOOL)adHasCustomMarketPlace SWIFT_WARN_UNUSED_RESULT;
- (void)handlingCustomMarketPlaceWithCompletion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5HyBid27HyBidAdAttributionParameter")
@interface HyBidAdAttributionParameter : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull jwt;)
+ (NSString * _Nonnull)jwt SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull custom_market_place;)
+ (NSString * _Nonnull)custom_market_place SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull reengagement_url;)
+ (NSString * _Nonnull)reengagement_url SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SKOverlayAppConfiguration;
SWIFT_CLASS("_TtC5HyBid34HyBidAdAttributionSKOverlayManager") SWIFT_AVAILABILITY(ios,introduced=17.4)
@interface HyBidAdAttributionSKOverlayManager : NSObject
- (void)getAppConfigurationWithAppIdentifier:(NSString * _Nullable)appIdentifier position:(enum SKOverlayPosition)position userDismissible:(BOOL)userDismissible ad:(HyBidAd * _Nonnull)ad adFormat:(NSString * _Nonnull)adFormat completionHandler:(void (^ _Nonnull)(SKOverlayAppConfiguration * _Nullable))completionHandler;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class NSNumber;
SWIFT_CLASS("_TtC5HyBid18HyBidAdSessionData")
@interface HyBidAdSessionData : NSObject
@property (nonatomic, copy) NSString * _Nullable creativeId;
@property (nonatomic, copy) NSString * _Nullable campaignId;
@property (nonatomic, copy) NSString * _Nullable bidPrice;
@property (nonatomic, copy) NSString * _Nullable adFormat;
@property (nonatomic, copy) NSString * _Nullable renderingStatus;
@property (nonatomic, strong) NSNumber * _Nullable viewability;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid25HyBidAppImpressionWrapper") SWIFT_AVAILABILITY(ios,introduced=17.4)
@interface HyBidAppImpressionWrapper : NSObject
+ (void)createWithAd:(HyBidAd * _Nullable)ad adFormat:(NSString * _Nonnull)adFormat completionHandler:(void (^ _Nonnull)(HyBidAppImpressionWrapper * _Nullable))completionHandler;
- (void)createWithAd:(HyBidAd * _Nullable)ad adFormat:(NSString * _Nonnull)adFormat completion:(void (^ _Nonnull)(HyBidAppImpressionWrapper * _Nullable))completion;
/// Begin view with the internally held AppImpression
- (void)beginViewForAdFormat:(NSString * _Nonnull)adFormat completion:(void (^ _Nonnull)(BOOL))completion;
/// End view with the internally held AppImpression
- (void)endViewForAdFormat:(NSString * _Nonnull)adFormat completion:(void (^ _Nonnull)(BOOL))completion;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum HyBidCTASize : int32_t;
enum HyBidCTALocation : int32_t;
@class UIImage;
SWIFT_CLASS("_TtC5HyBid12HyBidCTAData")
@interface HyBidCTAData : NSObject
/// The size of the CTA.
@property (nonatomic, readonly) enum HyBidCTASize size;
/// The location of the CTA.
@property (nonatomic, readonly) enum HyBidCTALocation location;
@property (nonatomic, readonly) CGFloat cornerRadius;
/// Initializes a new instance of <code>HyBidCTAData</code> with the specified size and location.
/// \param size The size of the CTA, represented by the <code>HyBidCTASize</code> enum.
///
/// \param location The location of the CTA, represented by the <code>HyBidCTALocation</code> enum.
///
- (nonnull instancetype)initWithSize:(enum HyBidCTASize)size location:(enum HyBidCTALocation)location OBJC_DESIGNATED_INITIALIZER;
+ (enum HyBidCTASize)sizeFromValue:(id _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
+ (enum HyBidCTALocation)locationFromValue:(id _Nonnull)value SWIFT_WARN_UNUSED_RESULT;
- (CGSize)sizeValue SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)fontSize SWIFT_WARN_UNUSED_RESULT;
- (UIImage * _Nonnull)ctaImageWithFixedSizeWithImage:(UIImage * _Nonnull)image SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)locationBottomConstraint SWIFT_WARN_UNUSED_RESULT;
- (CGFloat)locationLeadingConstraint SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nonnull)accessibilityIdentifierString SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

typedef SWIFT_ENUM(int32_t, HyBidCTALocation, open) {
  HyBidCTALocationDefault SWIFT_COMPILE_NAME("defaultLocation") = 0,
  HyBidCTALocationBottom_down = 1,
  HyBidCTALocationBottom_up = 2,
};

typedef SWIFT_ENUM(int32_t, HyBidCTASize, open) {
  HyBidCTASizeDefault SWIFT_COMPILE_NAME("defaultSize") = 0,
  HyBidCTASizeMedium = 1,
  HyBidCTASizeLarge = 2,
};

SWIFT_CLASS("_TtC5HyBid18HyBidConsentConfig")
@interface HyBidConsentConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidConsentConfig * _Nonnull sharedConfig;)
+ (HyBidConsentConfig * _Nonnull)sharedConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) BOOL coppa;
@end

@class HyBidSkipOffset;
SWIFT_CLASS("_TtC5HyBid14HyBidConstants")
@interface HyBidConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull HYBID_SDK_NAME;)
+ (NSString * _Nonnull)HYBID_SDK_NAME SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull HYBID_OMSDK_VERSION;)
+ (NSString * _Nonnull)HYBID_OMSDK_VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull HYBID_SDK_VERSION;)
+ (NSString * _Nonnull)HYBID_SDK_VERSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull HYBID_OMSDK_IDENTIFIER;)
+ (NSString * _Nonnull)HYBID_OMSDK_IDENTIFIER SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull RENDERING_SUCCESS;)
+ (NSString * _Nonnull)RENDERING_SUCCESS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull AD_SESSION_DATA;)
+ (NSString * _Nonnull)AD_SESSION_DATA SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PERCENT_VISIBLE;)
+ (NSString * _Nonnull)PERCENT_VISIBLE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL mraidExpand;)
+ (BOOL)mraidExpand SWIFT_WARN_UNUSED_RESULT;
+ (void)setMraidExpand:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL showEndCard;)
+ (BOOL)showEndCard SWIFT_WARN_UNUSED_RESULT;
+ (void)setShowEndCard:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL showCustomEndCard;)
+ (BOOL)showCustomEndCard SWIFT_WARN_UNUSED_RESULT;
+ (void)setShowCustomEndCard:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull customEndCardInputValue;)
+ (NSString * _Nonnull)customEndCardInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomEndCardInputValue:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) HyBidCustomEndcardDisplayBehaviour customEndcardDisplay;)
+ (HyBidCustomEndcardDisplayBehaviour)customEndcardDisplay SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomEndcardDisplay:(HyBidCustomEndcardDisplayBehaviour)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL interstitialCloseOnFinish;)
+ (BOOL)interstitialCloseOnFinish SWIFT_WARN_UNUSED_RESULT;
+ (void)setInterstitialCloseOnFinish:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL rewardedCloseOnFinish;)
+ (BOOL)rewardedCloseOnFinish SWIFT_WARN_UNUSED_RESULT;
+ (void)setRewardedCloseOnFinish:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull rewardedHtmlSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)rewardedHtmlSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setRewardedHtmlSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull rewardedVideoSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)rewardedVideoSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setRewardedVideoSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull interstitialHtmlSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)interstitialHtmlSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setInterstitialHtmlSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull pcInterstitialHtmlSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)pcInterstitialHtmlSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setPcInterstitialHtmlSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull videoSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)videoSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setVideoSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull pcVideoSkipOffset;)
+ (HyBidSkipOffset * _Nonnull)pcVideoSkipOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setPcVideoSkipOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) HyBidInterstitialActionBehaviour interstitialActionBehaviour;)
+ (HyBidInterstitialActionBehaviour)interstitialActionBehaviour SWIFT_WARN_UNUSED_RESULT;
+ (void)setInterstitialActionBehaviour:(HyBidInterstitialActionBehaviour)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull endCardCloseOffset;)
+ (HyBidSkipOffset * _Nonnull)endCardCloseOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setEndCardCloseOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull endCardCloseMaxOffset;)
+ (HyBidSkipOffset * _Nonnull)endCardCloseMaxOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setEndCardCloseMaxOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) HyBidSkipOffset * _Nonnull nativeCloseButtonOffset;)
+ (HyBidSkipOffset * _Nonnull)nativeCloseButtonOffset SWIFT_WARN_UNUSED_RESULT;
+ (void)setNativeCloseButtonOffset:(HyBidSkipOffset * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) HyBidAudioStatus audioStatus;)
+ (HyBidAudioStatus)audioStatus SWIFT_WARN_UNUSED_RESULT;
+ (void)setAudioStatus:(HyBidAudioStatus)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL creativeAutoStorekitEnabled;)
+ (BOOL)creativeAutoStorekitEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)setCreativeAutoStorekitEnabled:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL sdkAutoStorekitEnabled;)
+ (BOOL)sdkAutoStorekitEnabled SWIFT_WARN_UNUSED_RESULT;
+ (void)setSdkAutoStorekitEnabled:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, strong) NSDictionary * _Nonnull skAdNetworkModelInputValue;)
+ (NSDictionary * _Nonnull)skAdNetworkModelInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setSkAdNetworkModelInputValue:(NSDictionary * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull itunesIdValue;)
+ (NSString * _Nonnull)itunesIdValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setItunesIdValue:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull customCTAInputValue;)
+ (NSString * _Nonnull)customCTAInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomCTAInputValue:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull customBundleId;)
+ (NSString * _Nonnull)customBundleId SWIFT_WARN_UNUSED_RESULT;
+ (void)setCustomBundleId:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL iconSizeReducedInputValue;)
+ (BOOL)iconSizeReducedInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setIconSizeReducedInputValue:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull navigationModeInputValue;)
+ (NSString * _Nonnull)navigationModeInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setNavigationModeInputValue:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) BOOL landingPageInputValue;)
+ (BOOL)landingPageInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setLandingPageInputValue:(BOOL)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull ctaSizeTypeInputValue;)
+ (NSString * _Nonnull)ctaSizeTypeInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setCtaSizeTypeInputValue:(NSString * _Nonnull)value;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull ctaLocationTypeInputValue;)
+ (NSString * _Nonnull)ctaLocationTypeInputValue SWIFT_WARN_UNUSED_RESULT;
+ (void)setCtaLocationTypeInputValue:(NSString * _Nonnull)value;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class HyBidDataModel;

SWIFT_CLASS("_TtC5HyBid22HyBidCustomCTATracking")
@interface HyBidCustomCTATracking : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithAd:(HyBidAd * _Nonnull)ad OBJC_DESIGNATED_INITIALIZER;
- (NSArray<HyBidDataModel *> * _Nonnull)impressionBeacons SWIFT_WARN_UNUSED_RESULT;
- (NSArray<HyBidDataModel *> * _Nonnull)clickBeacons SWIFT_WARN_UNUSED_RESULT;
- (NSArray<HyBidDataModel *> * _Nonnull)endCardClickBeacons SWIFT_WARN_UNUSED_RESULT;
@end

@class NSCoder;
@class UIViewController;
@protocol HyBidCustomCTAViewDelegate;

SWIFT_CLASS("_TtC5HyBid18HyBidCustomCTAView")
@interface HyBidCustomCTAView : UIView
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
- (nonnull instancetype)initWithAd:(HyBidAd * _Nonnull)ad viewController:(UIViewController * _Nonnull)viewController delegate:(id <HyBidCustomCTAViewDelegate> _Nonnull)delegate adFormat:(NSString * _Nonnull)adFormat OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

SWIFT_PROTOCOL("_TtP5HyBid25HyBidInterruptionDelegate_")
@protocol HyBidInterruptionDelegate <NSObject>
@optional
- (void)adHasNoFocus;
- (void)adHasFocus;
- (void)vastEndCardWillShow;
- (void)vastCustomEndCardWillShow;
- (void)willEnterForeground;
- (void)feedbackViewWillShow;
- (void)feedbackViewDidDismiss;
- (void)productViewControllerIsReadyToShow;
- (void)productViewControllerWillShow;
- (void)productViewControllerDidShow;
- (void)productViewControllerDidFailWithError:(NSError * _Nonnull)error;
- (void)productViewControllerDidFinish;
- (void)internalWebBrowserDidShow;
@end

@interface HyBidCustomCTAView (SWIFT_EXTENSION(HyBid)) <HyBidInterruptionDelegate>
- (void)adHasFocus;
- (void)adHasNoFocus;
@end

@interface HyBidCustomCTAView (SWIFT_EXTENSION(HyBid))
- (void)presentCustomCTAWithDelay;
- (void)removeCustomCTA;
- (void)changeDelegateFor:(id <HyBidCustomCTAViewDelegate> _Nonnull)delegate;
+ (BOOL)isCustomCTAValidWithAd:(HyBidAd * _Nonnull)ad SWIFT_WARN_UNUSED_RESULT;
@end

enum HyBidGDPRk : NSInteger;

SWIFT_CLASS("_TtC5HyBid9HyBidGDPR")
@interface HyBidGDPR : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
+ (NSString * _Nonnull)stringValueForKey:(enum HyBidGDPRk)key SWIFT_WARN_UNUSED_RESULT;
+ (NSArray<NSString *> * _Nonnull)allGDPRKeys SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM_NAMED(NSInteger, HyBidGDPRk, "HyBidGDPRKeys", open) {
  HyBidGDPRkCCPAPrivacyKey = 0,
  HyBidGDPRkGDPRConsentKey = 1,
  HyBidGDPRkGDPRAppliesKey = 2,
  HyBidGDPRkCCPAPublicPrivacyKey = 3,
  HyBidGDPRkGDPRPublicConsentKey = 4,
  HyBidGDPRkGDPRPublicConsentV2Key = 5,
  HyBidGDPRkGPPPublicString = 6,
  HyBidGDPRkGPPPublicID = 7,
  HyBidGDPRkGPPString = 8,
  HyBidGDPRkGPPID = 9,
};


SWIFT_CLASS("_TtC5HyBid24HyBidImpressionConstants")
@interface HyBidImpressionConstants : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PLACEMENT_POSITION_UNKNOWN;)
+ (NSString * _Nonnull)PLACEMENT_POSITION_UNKNOWN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PLACEMENT_POSITION_FULLSCREEN;)
+ (NSString * _Nonnull)PLACEMENT_POSITION_FULLSCREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EXPANDABLE_DIRECTION_FULLSCREEN;)
+ (NSString * _Nonnull)EXPANDABLE_DIRECTION_FULLSCREEN SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull EXPANDABLE_DIRECTION_RESIZE_MINIMIZE;)
+ (NSString * _Nonnull)EXPANDABLE_DIRECTION_RESIZE_MINIMIZE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLACEMENT_TYPE_INTERSTITIAL;)
+ (NSString * _Nonnull)VIDEO_PLACEMENT_TYPE_INTERSTITIAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLACEMENT_SUBTYPE_INTERSTITIAL;)
+ (NSString * _Nonnull)VIDEO_PLACEMENT_SUBTYPE_INTERSTITIAL SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLACEMENT_SUBTYPE_STANDALONE;)
+ (NSString * _Nonnull)VIDEO_PLACEMENT_SUBTYPE_STANDALONE SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLAYBACK_METHOD_PAGE_LOAD_SOUND_ON;)
+ (NSString * _Nonnull)VIDEO_PLAYBACK_METHOD_PAGE_LOAD_SOUND_ON SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLAYBACK_METHOD_PAGE_LOAD_SOUND_OFF;)
+ (NSString * _Nonnull)VIDEO_PLAYBACK_METHOD_PAGE_LOAD_SOUND_OFF SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLAYBACK_METHOD_ENTER_VIEWPORT_SOUND_ON;)
+ (NSString * _Nonnull)VIDEO_PLAYBACK_METHOD_ENTER_VIEWPORT_SOUND_ON SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull VIDEO_PLAYBACK_METHOD_ENTER_VIEWPORT_SOUND_OFF;)
+ (NSString * _Nonnull)VIDEO_PLAYBACK_METHOD_ENTER_VIEWPORT_SOUND_OFF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid23HyBidInternalWebBrowser")
@interface HyBidInternalWebBrowser : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidInternalWebBrowser * _Nonnull shared;)
+ (HyBidInternalWebBrowser * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isInternalBrowserBeingPresented;
- (void)navigateToURL:(NSString * _Nonnull)url;
- (HyBidWebBrowserNavigation)webBrowserNavigationBehaviourFromString:(NSString * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HyBidAdFeedbackViewDelegate;
SWIFT_CLASS("_TtC5HyBid24HyBidInterruptionHandler")
@interface HyBidInterruptionHandler : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidInterruptionHandler * _Nonnull shared;)
+ (HyBidInterruptionHandler * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, weak) id <HyBidInterruptionDelegate> _Nullable delegate;
@property (nonatomic, weak) id <HyBidInterruptionDelegate> _Nullable overlappingElementDelegate;
@property (nonatomic, weak) id <HyBidAdFeedbackViewDelegate> _Nullable feedbackViewDelegate;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
- (BOOL)hasOnlyAppLifeCycleInterruption SWIFT_WARN_UNUSED_RESULT;
@end

@interface HyBidInterruptionHandler (SWIFT_EXTENSION(HyBid))
- (void)vastEndCardWillShow;
- (void)vastCustomEndCardWillShow;
@end

@interface HyBidInterruptionHandler (SWIFT_EXTENSION(HyBid))
- (void)productViewControllerDidFailWithError:(NSError * _Nonnull)error;
@end

@interface HyBidInterruptionHandler (SWIFT_EXTENSION(HyBid)) <HyBidAdFeedbackViewDelegate>
- (void)adFeedbackViewDidLoad;
- (void)adFeedbackViewWillShow;
- (void)adFeedbackViewDidShow;
- (void)adFeedbackViewDidFailWithError:(NSError * _Nonnull)error;
- (void)adFeedbackViewDidDismiss;
@end

@protocol HyBidInterstitialAdDelegate;

SWIFT_CLASS("_TtC5HyBid19HyBidInterstitialAd")
@interface HyBidInterstitialAd : NSObject
@property (nonatomic, strong) HyBidAd * _Nullable ad;
@property (nonatomic) BOOL isReady;
@property (nonatomic) BOOL isMediation;
@property (nonatomic) BOOL isAutoCacheOnLoad;
- (nonnull instancetype)initWithDelegate:(id <HyBidInterstitialAdDelegate> _Nonnull)delegate;
- (nonnull instancetype)initWithZoneID:(NSString * _Nullable)zoneID andWithDelegate:(id <HyBidInterstitialAdDelegate> _Nonnull)delegate;
- (nonnull instancetype)initWithZoneID:(NSString * _Nullable)zoneID withAppToken:(NSString * _Nullable)appToken andWithDelegate:(id <HyBidInterstitialAdDelegate> _Nonnull)delegate;
- (void)setOpenRTBAdTypeWithAdFormat:(HyBidOpenRTBAdType)adFormat;
- (void)load;
- (void)loadExchangeAd;
- (void)prepare;
- (void)setMediationVendor:(NSString * _Nonnull)mediationVendor;
- (void)prepareAdWithContent:(NSString * _Nonnull)adContent;
- (void)prepareAdWithAdReponse:(NSString * _Nonnull)adReponse;
- (void)prepareExchangeAdWithAdReponse:(NSString * _Nonnull)adReponse;
- (void)prepareVideoTagFrom:(NSString * _Nonnull)url;
- (void)prepareCustomMarkupFrom:(NSString * _Nonnull)markup;
- (void)show;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP5HyBid27HyBidInterstitialAdDelegate_")
@protocol HyBidInterstitialAdDelegate
- (void)interstitialDidLoad;
- (void)interstitialDidFailWithError:(NSError * _Null_unspecified)error;
- (void)interstitialDidTrackImpression;
- (void)interstitialDidTrackClick;
- (void)interstitialDidDismiss;
@end

enum HyBidLandingBehaviourType : int32_t;

SWIFT_CLASS("_TtC5HyBid21HyBidLandingBehaviour")
@interface HyBidLandingBehaviour : NSObject
- (enum HyBidLandingBehaviourType)convertStringWithValue:(NSString * _Nullable)value SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

typedef SWIFT_ENUM(int32_t, HyBidLandingBehaviourType, open) {
  HyBidLandingBehaviourTypeInstantCloseButton = 0,
  HyBidLandingBehaviourTypeNoCountdown = 1,
  HyBidLandingBehaviourTypeCountdown = 2,
  HyBidLandingBehaviourTypeUnknown = 3,
};


SWIFT_CLASS("_TtC5HyBid19HyBidLocationConfig")
@interface HyBidLocationConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidLocationConfig * _Nonnull sharedConfig;)
+ (HyBidLocationConfig * _Nonnull)sharedConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) BOOL locationTrackingEnabled;
@property (nonatomic) BOOL locationUpdatesEnabled;
@end


SWIFT_CLASS("_TtC5HyBid11HyBidLogger")
@interface HyBidLogger : NSObject
+ (void)setLogLevel:(HyBidLogLevel)logLevel;
+ (void)errorLogFromClass:(NSString * _Nonnull)className fromMethod:(NSString * _Nonnull)fromMethod withMessage:(NSString * _Nonnull)withMessage;
+ (void)warningLogFromClass:(NSString * _Nonnull)className fromMethod:(NSString * _Nonnull)fromMethod withMessage:(NSString * _Nonnull)withMessage;
+ (void)infoLogFromClass:(NSString * _Nonnull)className fromMethod:(NSString * _Nonnull)fromMethod withMessage:(NSString * _Nonnull)withMessage;
+ (void)debugLogFromClass:(NSString * _Nonnull)className fromMethod:(NSString * _Nonnull)fromMethod withMessage:(NSString * _Nonnull)withMessage;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC5HyBid23HyBidMRAIDCloseCardView")
@interface HyBidMRAIDCloseCardView : UIView
- (nonnull instancetype)initWithDictionary:(NSDictionary * _Nonnull)dictionary OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder SWIFT_UNAVAILABLE;
- (void)didMoveToSuperview;
- (nonnull instancetype)initWithFrame:(CGRect)frame SWIFT_UNAVAILABLE;
@end

@interface HyBidMRAIDCloseCardView (SWIFT_EXTENSION(HyBid)) <HyBidContentInfoViewDelegate>
- (void)contentInfoViewWidthNeedsUpdate:(NSNumber * _Null_unspecified)width;
@end

enum HyBidMRAIDCommandType : int32_t;

SWIFT_CLASS("_TtC5HyBid17HyBidMRAIDCommand")
@interface HyBidMRAIDCommand : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (enum HyBidMRAIDCommandType)commandTypeWithText:(NSString * _Nonnull)text SWIFT_WARN_UNUSED_RESULT;
@end

typedef SWIFT_ENUM(int32_t, HyBidMRAIDCommandType, open) {
  HyBidMRAIDCommandTypeMraid = 0,
  HyBidMRAIDCommandTypeVerveAdExperience = 1,
  HyBidMRAIDCommandTypeConsoleLog = 2,
  HyBidMRAIDCommandTypeUnknown = 3,
};

typedef SWIFT_ENUM(NSInteger, HyBidOnTopOfType, open) {
  HyBidOnTopOfTypeUNKNOWN_TOP_EVENT = 0,
  HyBidOnTopOfTypeDISPLAY = 1,
  HyBidOnTopOfTypeCOMPANION_AD = 2,
  HyBidOnTopOfTypeCUSTOM_ENDCARD = 3,
};

@class PNLiteAdRequestModel;

SWIFT_CLASS("_TtC5HyBid24HyBidOpenRTBRequestModel")
@interface HyBidOpenRTBRequestModel : NSObject
- (nonnull instancetype)initWithAdRequestModel:(PNLiteAdRequestModel * _Nonnull)adRequestModel openRTBAdType:(HyBidOpenRTBAdType)openRTBAdType OBJC_DESIGNATED_INITIALIZER;
- (NSDictionary<NSString *, id> * _Nonnull)getOpenRTBRequestBody SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5HyBid20HyBidReportingBeacon")
@interface HyBidReportingBeacon : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable properties;
@property (nonatomic, copy) NSString * _Nonnull beaconType;
- (nonnull instancetype)initWith:(NSString * _Nonnull)beaconType properties:(NSDictionary<NSString *, id> * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@class HyBidReportingEvent;
@class HyBidReportingVASTTracker;

SWIFT_PROTOCOL("_TtP5HyBid22HyBidReportingDelegate_")
@protocol HyBidReportingDelegate
- (void)onEventWith:(HyBidReportingEvent * _Nonnull)event;
- (void)onBeaconWith:(HyBidReportingBeacon * _Nonnull)beacon;
- (void)onVASTTrackerWith:(HyBidReportingVASTTracker * _Nonnull)tracker;
@end


SWIFT_CLASS("_TtC5HyBid19HyBidReportingEvent")
@interface HyBidReportingEvent : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable properties;
@property (nonatomic, copy) NSString * _Nonnull eventType;
- (nonnull instancetype)initWith:(NSString * _Nonnull)eventType adFormat:(NSString * _Nullable)adFormat properties:(NSDictionary<NSString *, id> * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWith:(NSString * _Nonnull)eventType errorMessage:(NSString * _Nullable)errorMessage properties:(NSDictionary<NSString *, id> * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5HyBid21HyBidReportingManager")
@interface HyBidReportingManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidReportingManager * _Nonnull sharedInstance;)
+ (HyBidReportingManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSArray<HyBidReportingEvent *> * _Nonnull events;
@property (nonatomic, weak) id <HyBidReportingDelegate> _Nullable delegate;
@property (nonatomic) BOOL isAtomStarted;
@property (nonatomic, copy) NSArray<HyBidReportingBeacon *> * _Nonnull beacons;
@property (nonatomic, copy) NSArray<HyBidReportingVASTTracker *> * _Nonnull vastTrackers;
- (void)reportEventFor:(HyBidReportingEvent * _Nonnull)event;
- (void)reportEventsFor:(NSArray<HyBidReportingEvent *> * _Nonnull)events;
- (void)clearAllReports;
- (void)clearEvents;
- (NSDictionary<NSString *, NSString *> * _Nonnull)addCommonPropertiesForAd:(HyBidAd * _Nullable)ad withRequest:(HyBidAdRequest * _Nullable)request SWIFT_WARN_UNUSED_RESULT;
- (void)reportBeaconFor:(HyBidReportingBeacon * _Nonnull)beacon;
- (void)clearBeacons;
- (void)reportVASTTrackerFor:(HyBidReportingVASTTracker * _Nonnull)tracker;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid25HyBidReportingVASTTracker")
@interface HyBidReportingVASTTracker : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nullable properties;
@property (nonatomic, copy) NSString * _Nonnull trackerType;
- (nonnull instancetype)initWith:(NSString * _Nonnull)trackerType properties:(NSDictionary<NSString *, id> * _Nullable)properties OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

@protocol HyBidRewardedAdDelegate;

SWIFT_CLASS("_TtC5HyBid15HyBidRewardedAd")
@interface HyBidRewardedAd : NSObject
@property (nonatomic, strong) HyBidAd * _Nullable ad;
@property (nonatomic) BOOL isReady;
@property (nonatomic) BOOL isMediation;
@property (nonatomic) BOOL isAutoCacheOnLoad;
- (nonnull instancetype)initWithDelegate:(id <HyBidRewardedAdDelegate> _Nonnull)delegate;
- (nonnull instancetype)initWithZoneID:(NSString * _Nullable)zoneID andWithDelegate:(id <HyBidRewardedAdDelegate> _Nonnull)delegate;
- (nonnull instancetype)initWithZoneID:(NSString * _Nullable)zoneID withAppToken:(NSString * _Nullable)appToken andWithDelegate:(id <HyBidRewardedAdDelegate> _Nonnull)delegate;
- (void)load;
- (void)loadExchangeAd;
- (void)setOpenRTBAdTypeWithAdFormat:(HyBidOpenRTBAdType)adFormat;
- (void)prepare;
- (void)setMediationVendor:(NSString * _Nonnull)mediationVendor;
- (void)prepareCustomMarkupFrom:(NSString * _Nonnull)markup;
- (void)prepareAdWithContent:(NSString * _Nonnull)adContent;
- (void)prepareExchangeAdWithAdReponse:(NSString * _Nonnull)adReponse;
- (void)prepareAdWithAdReponse:(NSString * _Nonnull)adReponse;
- (void)show;
- (void)showFromViewController:(UIViewController * _Nonnull)viewController;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_PROTOCOL("_TtP5HyBid23HyBidRewardedAdDelegate_")
@protocol HyBidRewardedAdDelegate
- (void)rewardedDidLoad;
- (void)rewardedDidFailWithError:(NSError * _Null_unspecified)error;
- (void)rewardedDidTrackImpression;
- (void)rewardedDidTrackClick;
- (void)rewardedDidDismiss;
- (void)onReward;
@end

@class HyBidTargetingModel;

SWIFT_CLASS("_TtC5HyBid14HyBidSDKConfig")
@interface HyBidSDKConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidSDKConfig * _Nonnull sharedConfig;)
+ (HyBidSDKConfig * _Nonnull)sharedConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) BOOL test;
@property (nonatomic) BOOL reporting;
@property (nonatomic) BOOL atomEnabled;
@property (nonatomic, strong) HyBidTargetingModel * _Nullable targeting;
@property (nonatomic, copy) NSString * _Nullable appToken;
@property (nonatomic, copy) NSString * _Nonnull apiURL;
@property (nonatomic, copy) NSString * _Nonnull openRtbApiURL;
@property (nonatomic, copy) NSString * _Nullable appID;
@property (nonatomic, copy) NSString * _Nullable customRemoteConfigURL;
@end

SWIFT_CLASS("_TtC5HyBid30HyBidSKAdNetworkViewController")
@interface HyBidSKAdNetworkViewController : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidSKAdNetworkViewController * _Nonnull shared;)
+ (HyBidSKAdNetworkViewController * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL avoidAutoStoreKitPresentationAfterReplay;
- (void)presentStoreKitViewWithProductParameters:(NSDictionary<NSString *, id> * _Nonnull)productParameters adFormat:(NSString * _Nonnull)adFormat isAutoStoreKitView:(BOOL)isAutoStoreKitView ad:(HyBidAd * _Nonnull)ad rootViewController:(UIViewController * _Nonnull)rootViewController;
- (void)presentStoreKitViewWithProductParameters:(NSDictionary<NSString *, id> * _Nonnull)productParameters adFormat:(NSString * _Nonnull)adFormat isAutoStoreKitView:(BOOL)isAutoStoreKitView ad:(HyBidAd * _Nonnull)ad;
- (BOOL)isSKProductViewControllerPresented SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@class SKStoreProductViewController;
@interface HyBidSKAdNetworkViewController (SWIFT_EXTENSION(HyBid)) <SKStoreProductViewControllerDelegate>
- (void)productViewControllerDidFinish:(SKStoreProductViewController * _Nonnull)viewController;
@end

SWIFT_CLASS("_TtC5HyBid19HyBidSessionManager")
@interface HyBidSessionManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidSessionManager * _Nonnull sharedInstance;)
+ (HyBidSessionManager * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull impressionCounter;
@property (nonatomic, copy) NSString * _Nonnull sessionDuration;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic, readonly, copy) NSDictionary<NSString *, NSNumber *> * _Nonnull safeImpressionCounter;
- (void)setStartSession;
- (void)updateSessionWithZoneID:(NSString * _Nonnull)zoneID;
- (void)incrementImpressionCounterWithZoneID:(NSString * _Nonnull)zoneID;
- (void)sessionDurationWithZoneID:(NSString * _Nonnull)zoneID;
- (void)setAgeOfAppSinceCreated;
- (NSString * _Nonnull)getAgeOfApp SWIFT_WARN_UNUSED_RESULT;
@end

@class CLLocationManager;
@class CLLocation;

SWIFT_CLASS("_TtC5HyBid13HyBidSettings")
@interface HyBidSettings : NSObject <CLLocationManagerDelegate>
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidSettings * _Nonnull sharedInstance;)
+ (HyBidSettings * _Nonnull)sharedInstance SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) BOOL supportMultipleFidelities;
@property (nonatomic, readonly, copy) NSString * _Nullable advertisingId;
@property (nonatomic, readonly, copy) NSString * _Nonnull os;
@property (nonatomic, readonly, copy) NSString * _Nonnull osVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceModel;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceModelIdentifier;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceMake;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceType;
@property (nonatomic, readonly, copy) NSString * _Nonnull screenHeightInPixelss;
@property (nonatomic, readonly, copy) NSString * _Nonnull screenWidthInPixels;
@property (nonatomic, readonly, copy) NSString * _Nonnull pxRatio;
@property (nonatomic, readonly, copy) NSString * _Nullable language;
@property (nonatomic, readonly, copy) NSString * _Nonnull jsValue;
- (void)locationManager:(CLLocationManager * _Nonnull)manager didChangeAuthorizationStatus:(CLAuthorizationStatus)status;
@property (nonatomic, readonly, copy) NSString * _Nullable languageBCP47;
@property (nonatomic, readonly, copy) NSString * _Nullable carrierName;
@property (nonatomic, readonly, copy) NSString * _Nullable carrierMCCMNC;
@property (nonatomic, readonly, copy) NSString * _Nonnull connectionType SWIFT_AVAILABILITY(ios,introduced=14.1);
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceWidth;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceHeight;
@property (nonatomic, readonly, copy) NSString * _Nonnull orientation;
@property (nonatomic, readonly, copy) NSString * _Nonnull deviceSound;
@property (nonatomic, readonly, strong) NSNumber * _Nonnull audioVolumePercentage;
@property (nonatomic, readonly, copy) NSString * _Nullable locale;
@property (nonatomic, copy) NSString * _Nullable sdkVersion;
@property (nonatomic, readonly, copy) NSString * _Nullable appBundleID;
@property (nonatomic, readonly, copy) NSString * _Nullable appVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull isDeviceCharging;
@property (nonatomic, readonly, copy) NSString * _Nullable batteryLevel;
@property (nonatomic, readonly, copy) NSString * _Nonnull batterySaver;
@property (nonatomic, readonly, strong) CLLocation * _Nullable location;
@property (nonatomic, readonly, copy) NSString * _Nullable identifierForVendor;
@property (nonatomic, readonly, copy) NSString * _Nullable ip;
@property (nonatomic, readonly, strong) NSNumber * _Nullable appTrackingTransparency;
@property (nonatomic, readonly, copy) NSString * _Nullable isDarkModeEnabled;
@property (nonatomic, readonly, copy) NSString * _Nullable isAirplaneModeEnabled;
@property (nonatomic, readonly) BOOL hasSIM;
@end


SWIFT_CLASS("_TtC5HyBid15HyBidSkipOffset")
@interface HyBidSkipOffset : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_VIDEO_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_VIDEO_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_HTML_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_HTML_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_REWARDED_HTML_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_REWARDED_HTML_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_SKIP_OFFSET_WITHOUT_ENDCARD;)
+ (NSInteger)DEFAULT_SKIP_OFFSET_WITHOUT_ENDCARD SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_END_CARD_CLOSE_OFFSET;)
+ (NSInteger)DEFAULT_END_CARD_CLOSE_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_END_CARD_CLOSE_MAX_OFFSET;)
+ (NSInteger)DEFAULT_END_CARD_CLOSE_MAX_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_REWARDED_VIDEO_MAX_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_REWARDED_VIDEO_MAX_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_INTERSTITIAL_VIDEO_MAX_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_INTERSTITIAL_VIDEO_MAX_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_REWARDED_HTML_MAX_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_REWARDED_HTML_MAX_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_INTERSTITIAL_HTML_MAX_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_INTERSTITIAL_HTML_MAX_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_NATIVE_CLOSE_BUTTON_OFFSET;)
+ (NSInteger)DEFAULT_NATIVE_CLOSE_BUTTON_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_PC_VIDEO_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_PC_VIDEO_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_PC_VIDEO_MAX_SKIP_OFFSET_COMPANION;)
+ (NSInteger)DEFAULT_PC_VIDEO_MAX_SKIP_OFFSET_COMPANION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_PC_VIDEO_MAX_SKIP_OFFSET_NON_COMPANION;)
+ (NSInteger)DEFAULT_PC_VIDEO_MAX_SKIP_OFFSET_NON_COMPANION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_PC_INTERSTITIAL_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_PC_INTERSTITIAL_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly) NSInteger DEFAULT_PC_INTERSTITIAL_MAX_SKIP_OFFSET;)
+ (NSInteger)DEFAULT_PC_INTERSTITIAL_MAX_SKIP_OFFSET SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, strong) NSNumber * _Nullable offset;
@property (nonatomic) BOOL isCustom;
@property (nonatomic, strong) NSNumber * _Nonnull style;
- (nonnull instancetype)initWithOffset:(NSNumber * _Nullable)offset isCustom:(BOOL)isCustom OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithOffset:(NSNumber * _Nullable)offset isCustom:(BOOL)isCustom style:(NSNumber * _Nonnull)style OBJC_DESIGNATED_INITIALIZER;
- (void)configureWithOffset:(NSNumber * _Nullable)offset isCustom:(BOOL)isCustom style:(NSNumber * _Nonnull)style;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC5HyBid19HyBidTargetingModel")
@interface HyBidTargetingModel : NSObject
@property (nonatomic, strong) NSNumber * _Nullable age;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull interests;
@property (nonatomic, copy) NSString * _Nullable gender;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

@protocol HyBidURLRedirectorDelegate;
@class HyBidSkAdNetworkModel;
@class NSURLSession;
@class NSURLSessionTask;
@class NSHTTPURLResponse;
@class NSURLRequest;
@class NSURLSessionDataTask;
@class NSURLResponse;

SWIFT_CLASS("_TtC5HyBid18HyBidURLRedirector")
@interface HyBidURLRedirector : NSObject <NSURLSessionDataDelegate>
@property (nonatomic, weak) id <HyBidURLRedirectorDelegate> _Nullable delegate;
@property (nonatomic, copy) NSString * _Nullable userAgent;
- (void)drillWithUrl:(NSString * _Nonnull)url skanModel:(HyBidSkAdNetworkModel * _Nullable)skanModel;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task willPerformHTTPRedirection:(NSHTTPURLResponse * _Nonnull)response newRequest:(NSURLRequest * _Nonnull)request completionHandler:(void (^ _Nonnull)(NSURLRequest * _Nullable))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session dataTask:(NSURLSessionDataTask * _Nonnull)dataTask didReceiveResponse:(NSURLResponse * _Nonnull)response completionHandler:(void (^ _Nonnull)(NSURLSessionResponseDisposition))completionHandler;
- (void)URLSession:(NSURLSession * _Nonnull)session task:(NSURLSessionTask * _Nonnull)task didCompleteWithError:(NSError * _Nullable)error;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_PROTOCOL("_TtP5HyBid26HyBidURLRedirectorDelegate_")
@protocol HyBidURLRedirectorDelegate
- (void)onURLRedirectorStartWithUrl:(NSString * _Nonnull)url;
- (void)onURLRedirectorRedirectWithUrl:(NSString * _Nonnull)url;
- (void)onURLRedirectorFinishWithUrl:(NSString * _Nonnull)url;
- (void)onURLRedirectorFailWithUrl:(NSString * _Nonnull)url withError:(NSError * _Nonnull)error;
@end


SWIFT_CLASS("_TtC5HyBid28HyBidVASTEventBeaconsManager")
@interface HyBidVASTEventBeaconsManager : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidVASTEventBeaconsManager * _Nonnull shared;)
+ (HyBidVASTEventBeaconsManager * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
- (void)reportVASTEventWithType:(NSString * _Nonnull)type ad:(HyBidAd * _Nullable)ad;
- (void)reportVASTEventWithType:(NSString * _Nonnull)type ad:(HyBidAd * _Nullable)ad errorCode:(NSInteger)errorCode;
- (void)reportVASTEventWithType:(NSString * _Nonnull)type ad:(HyBidAd * _Nullable)ad onTopOf:(enum HyBidOnTopOfType)onTopOf;
- (void)reportVASTEventWithType:(NSString * _Nonnull)type ad:(HyBidAd * _Nullable)ad onTopOf:(enum HyBidOnTopOfType)onTopOf errorCode:(NSInteger)errorCode;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

SWIFT_CLASS("_TtC5HyBid16HyBidVASTTracker")
@interface HyBidVASTTracker : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull type;
@property (nonatomic, readonly, copy) NSString * _Nonnull url;
@property (nonatomic, readonly, copy) NSString * _Nullable beaconName;
- (nonnull instancetype)initWithType:(NSString * _Nonnull)type url:(NSString * _Nonnull)url beaconName:(NSString * _Nullable)beaconName OBJC_DESIGNATED_INITIALIZER;
- (BOOL)shouldBeTriggered SWIFT_WARN_UNUSED_RESULT;
- (void)addToTriggeredTrackersList;
+ (void)cleanTriggeredTrackersList;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

SWIFT_CLASS("_TtC5HyBid21HyBidViewbilityConfig")
@interface HyBidViewbilityConfig : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) HyBidViewbilityConfig * _Nonnull sharedConfig;)
+ (HyBidViewbilityConfig * _Nonnull)sharedConfig SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@property (nonatomic) HyBidImpressionTrackerMethod impressionTrackerMethod;
@property (nonatomic) NSInteger minVisibleTime;
@property (nonatomic) double minVisiblePercent;
@end

@class UITouch;
@class UIEvent;
@interface SKStoreProductViewController (SWIFT_EXTENSION(HyBid))
- (void)viewDidAppear:(BOOL)animated;
- (void)dismissViewControllerAnimated:(BOOL)flag completion:(void (^ _Nullable)(void))completion;
- (void)viewDidDisappear:(BOOL)animated;
- (void)touchesBegan:(NSSet<UITouch *> * _Nonnull)touches withEvent:(UIEvent * _Nullable)event;
@property (nonatomic, readonly) UIInterfaceOrientationMask supportedInterfaceOrientations;
@property (nonatomic, readonly) BOOL shouldAutorotate;
@end

SWIFT_CLASS_NAMED("VASTBeacon")
@interface HyBidReportingVASTBeacon : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull BEACONS;)
+ (NSString * _Nonnull)BEACONS SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull ONTOPOF;)
+ (NSString * _Nonnull)ONTOPOF SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS_NAMED("VASTTrackerType")
@interface HyBidReportingVASTTrackerType : HyBidReportingProperties
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull IMPRESSION;)
+ (NSString * _Nonnull)IMPRESSION SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull COMPANION_CLICK_THROUGH;)
+ (NSString * _Nonnull)COMPANION_CLICK_THROUGH SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull CLICK_TRACKING;)
+ (NSString * _Nonnull)CLICK_TRACKING SWIFT_WARN_UNUSED_RESULT;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, copy) NSString * _Nonnull PROGRESS;)
+ (NSString * _Nonnull)PROGRESS SWIFT_WARN_UNUSED_RESULT;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
